# Generated by Django 5.2.1 on 2025-06-13 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=128)),
                ('auditorium_id', models.CharField(max_length=128)),
                ('counted_at', models.DateTimeField(auto_now_add=True)),
                ('people_count', models.IntegerField()),
            ],
        ),
    ]
